"""add wallet_id to transactions

Revision ID: 51084c6c07a1
Revises: 5e996d1e860b
Create Date: 2025-08-11 16:25:11.601491

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51084c6c07a1'
down_revision: Union[str, Sequence[str], None] = '5e996d1e860b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Добавляем колонку как nullable сначала
    op.add_column('transactions', sa.Column('wallet_id', sa.Integer(), nullable=True))
    
    # Обновляем существующие записи значением по умолчанию
    op.execute("UPDATE transactions SET wallet_id = 1 WHERE wallet_id IS NULL")
    
    # Теперь делаем колонку NOT NULL
    op.alter_column('transactions', 'wallet_id', nullable=False)
    
    op.create_foreign_key(None, 'transactions', 'wallets', ['wallet_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_column('transactions', 'wallet_id')
    # ### end Alembic commands ###
