"""initial_saldo

Revision ID: ad7d1f8d574d
Revises: 51084c6c07a1
Create Date: 2025-08-12 00:28:57.280336

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad7d1f8d574d'
down_revision: Union[str, Sequence[str], None] = '51084c6c07a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Добавляем created_at как nullable сначала
    op.add_column('transactions', sa.Column('created_at', sa.DateTime(), nullable=True))
    # Обновляем существующие записи
    op.execute("UPDATE transactions SET created_at = NOW() WHERE created_at IS NULL")
    # Делаем колонку NOT NULL
    op.alter_column('transactions', 'created_at', nullable=False)

    op.alter_column('transactions', 'wallet_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # Добавляем initial_saldo как nullable сначала
    op.add_column('wallets', sa.Column('initial_saldo', sa.Float(), nullable=True))
    # Обновляем существующие записи
    op.execute("UPDATE wallets SET initial_saldo = 0.0 WHERE initial_saldo IS NULL")
    # Делаем колонку NOT NULL
    op.alter_column('wallets', 'initial_saldo', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wallets', 'initial_saldo')
    op.alter_column('transactions', 'wallet_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('transactions', 'created_at')
    # ### end Alembic commands ###
